# PostgreSQL Configuration (Render)
spring.datasource.url=jdbc:postgresql://localhost:5432/expensetracker
#spring.datasource.url=jdbc:postgresql://dpg-d5e1no3e5dus739nj3pg-a.singapore-postgres.render.com:5432/expensetracker_tcfg
spring.datasource.username=root
spring.datasource.password=8979985527

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true










